import org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformExtension
import org.jetbrains.kotlin.gradle.dsl.JvmDefaultMode
import org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension
import org.jetbrains.kotlin.gradle.dsl.KotlinVersion

plugins {
    alias(libs.plugins.kotlin.jvm) apply false
    // klibs - core
    alias(libs.plugins.klibs.gradle.detekt) apply false
    alias(libs.plugins.klibs.gradle.java.version) apply false
    alias(libs.plugins.klibs.gradle.rootinfo) apply false
}

apply(plugin = "ru.astrainteractive.gradleplugin.detekt")
apply(plugin = "ru.astrainteractive.gradleplugin.rootinfo")

tasks.withType<dev.detekt.gradle.Detekt>().configureEach {
    // The IntelliJ Platform sandbox is generated by :plugin:prepareSandbox and must not be analysed
    exclude("**/.intellijPlatform/**")
}

subprojects {
    plugins.withId("org.jetbrains.kotlin.jvm") {
        apply(plugin = "ru.astrainteractive.gradleplugin.java.version")
        extensions.configure<KotlinJvmProjectExtension> {
            // Compile and run tests on the JDK the target platform runs on, whatever JVM Gradle itself uses
            jvmToolchain(providers.gradleProperty("klibs.java.ktarget").get().toInt())
            compilerOptions {
                // Match the Kotlin runtime bundled with the target IntelliJ Platform
                apiVersion.set(KotlinVersion.KOTLIN_2_1)
                languageVersion.set(KotlinVersion.KOTLIN_2_1)
                // Without JVM default methods Kotlin emits bridges to DefaultImpls of platform interfaces
                // (ToolWindowFactory and others), which the Plugin Verifier reports as internal API overrides.
                // Every module is merged into one JAR, so all of them use the same mode.
                jvmDefault.set(JvmDefaultMode.NO_COMPATIBILITY)
            }
        }
        tasks.withType<Test>().configureEach {
            useJUnitPlatform()
        }
    }
    // Both the main plugin and the module plugin register this extension
    plugins.withId("org.jetbrains.intellij.platform.module") {
        extensions.configure<IntelliJPlatformExtension> {
            // No Swing forms and no @NotNull assertions to instrument; the task also fails on some macOS JDK layouts
            instrumentCode = false
        }
    }
    plugins.withId("org.jetbrains.intellij.platform") {
        extensions.configure<IntelliJPlatformExtension> {
            instrumentCode = false
        }
    }
}
