plugins {
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.intellij.platform) apply false
    alias(libs.plugins.intellij.platform.module) apply false
    // klibs - core
    alias(libs.plugins.klibs.gradle.detekt) apply false
    alias(libs.plugins.klibs.gradle.java.version) apply false
    alias(libs.plugins.klibs.gradle.rootinfo) apply false
}

apply(plugin = "ru.astrainteractive.gradleplugin.detekt")
apply(plugin = "ru.astrainteractive.gradleplugin.rootinfo")

// detekt CLI and rule sets are resolved by the root project
repositories {
    mavenCentral()
}

tasks.withType<dev.detekt.gradle.Detekt>().configureEach {
    // The IntelliJ Platform sandbox is generated by :plugin:prepareSandbox and must not be analysed
    exclude("**/.intellijPlatform/**")
}

subprojects.forEach { subproject ->
    subproject.plugins.withId("org.jetbrains.kotlin.jvm") {
        subproject.apply(plugin = "ru.astrainteractive.gradleplugin.java.version")
    }
}
