# Gradle
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m
kotlin.incremental=true
kotlin.stdlib.default.dependency=false
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.isolated-projects=false
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.tooling.parallel=true
# Java
klibs.java.source=25
klibs.java.target=25
klibs.java.ktarget=25
# Project
klibs.project.name=compose-html-preview
klibs.project.group=com.makeevrserg.compose.html.preview
klibs.project.version.string=0.1.0
klibs.project.description=IntelliJ plugin that previews Compose HTML (DOM) composables inside the IDE
klibs.project.developers=makeevrserg|Makeev Roman|makeevrserg@gmail.com
klibs.project.url=https://github.com/makeevrserg/MVIKotlin-Decompose-Plugin
# IntelliJ
intellij.version=2026.2.1
intellij.sinceBuild=262
