package com.makeevrserg.compose.html.preview.harness.generator

import com.makeevrserg.compose.html.preview.harness.HarnessPreview
import com.makeevrserg.compose.html.preview.harness.PreviewModulePlan
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class PreviewRegistryFactoryTest {
    private val factory = PreviewRegistryFactory(HarnessNaming())

    private val module = PreviewModulePlan(
        gradlePath = ":components:ui",
        directory = "/project/components/ui",
        previews = listOf(HarnessPreview("com.example.CardPreview"), HarnessPreview("com.example.ButtonPreview"))
    )

    @Test
    fun GIVEN_module_previews_WHEN_create_THEN_the_file_lands_in_the_package_of_the_module() {
        val file = factory.create(module)

        assertEquals(
            "kotlin/composehtmlpreview/generated/m_components_ui/PreviewRegistry.kt",
            file.relativePath
        )
        assertTrue(file.content.startsWith("// Generated by the Compose HTML Preview plugin"), file.content)
        assertTrue(file.content.contains("package composehtmlpreview.generated.m_components_ui"), file.content)
    }

    @Suppress("StringShouldBeRawString")
    @Test
    fun GIVEN_module_previews_WHEN_create_THEN_every_preview_is_listed_and_callable() {
        val content = factory.create(module).content

        assertTrue(content.contains("        \"com.example.CardPreview\","), content)
        assertTrue(content.contains("        \"com.example.ButtonPreview\"\n"), content)
        assertTrue(content.contains("            \"com.example.CardPreview\" -> com.example.CardPreview()"), content)
    }
}
