package com.makeevrserg.kaleidos.harness.generator

import com.makeevrserg.kaleidos.harness.HarnessLayout
import com.makeevrserg.kaleidos.harness.HarnessPreview

/**
 * Names of the generated code. Every module gets its own registry package, so the same class name can
 * be generated into as many modules as the page needs without them colliding on the classpath.
 */
class HarnessNaming {

    /** `:components:lib-kobweb:ui` becomes `m_components_lib_kobweb_ui`, a valid package segment. */
    private fun moduleSegment(gradlePath: String): String {
        val sanitized = gradlePath.map { character ->
            if (character.isLetterOrDigit()) character.lowercaseChar() else '_'
        }
        return MODULE_SEGMENT_PREFIX + sanitized.joinToString(separator = "")
    }

    private fun identifier(value: String): String {
        return value.map { character -> if (character.isLetterOrDigit()) character else '_' }
            .joinToString(separator = "")
    }

    fun functionName(preview: HarnessPreview): String = preview.fqn.substringAfterLast(FQN_SEPARATOR)

    fun privatePreviewWrapperName(preview: HarnessPreview): String {
        val file = identifier(preview.sourcePath.removeSuffix(KOTLIN_EXTENSION))
        return "$PRIVATE_PREVIEW_WRAPPER_PREFIX${file}_${functionName(preview)}"
    }

    fun callFqn(preview: HarnessPreview): String {
        if (!preview.isPrivate) return preview.fqn
        val packageName = preview.fqn.substringBeforeLast(FQN_SEPARATOR, missingDelimiterValue = "")
        val wrapperName = privatePreviewWrapperName(preview)
        if (packageName.isEmpty()) return wrapperName
        return "$packageName$FQN_SEPARATOR$wrapperName"
    }

    fun privatePreviewFileCopyPath(sourcePath: String): String {
        return "${HarnessLayout.KOTLIN_DIRECTORY}/$PRIVATE_PREVIEW_FILES_DIRECTORY/$sourcePath"
    }

    fun registryPackage(gradlePath: String): String = "$PAGE_PACKAGE.${moduleSegment(gradlePath)}"

    fun registryFqn(gradlePath: String): String = "${registryPackage(gradlePath)}.$REGISTRY_CLASS"

    fun packageDirectory(packageName: String): String = packageName.replace('.', '/')

    companion object {
        const val PAGE_PACKAGE = "kaleidos.generated"
        const val REGISTRY_CLASS = "PreviewRegistry"
        const val HEADER = "// Generated by the Kaleidos plugin. Do not edit, do not commit."
        private const val MODULE_SEGMENT_PREFIX = "m"
        private const val FQN_SEPARATOR = '.'
        private const val KOTLIN_EXTENSION = ".kt"
        private const val PRIVATE_PREVIEW_WRAPPER_PREFIX = "KaleidosPreview_"
        private const val PRIVATE_PREVIEW_FILES_DIRECTORY = "kaleidos/sources"
    }
}
