[versions]
# Kotlin
kotlin-version = "2.3.20" # https://github.com/JetBrains/kotlin
# IntelliJ
intellij-platform-gradle = "2.18.1" # https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html
# klibs
klibs-gradleplugin = "2.0.0" # https://github.com/makeevrserg/gradle-plugin

[plugins]
# Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
# IntelliJ
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform-gradle" }
intellij-platform-module = { id = "org.jetbrains.intellij.platform.module", version.ref = "intellij-platform-gradle" }
# klibs - core
klibs-gradle-detekt = { id = "ru.astrainteractive.gradleplugin.detekt", version.ref = "klibs-gradleplugin" }
klibs-gradle-java-version = { id = "ru.astrainteractive.gradleplugin.java.version", version.ref = "klibs-gradleplugin" }
klibs-gradle-rootinfo = { id = "ru.astrainteractive.gradleplugin.rootinfo", version.ref = "klibs-gradleplugin" }
