package com.makeevrserg.compose.html.preview.harness.generator

/**
 * Names of the generated code. Every module gets its own registry package, so the same class name can
 * be generated into as many modules as the page needs without them colliding on the classpath.
 */
class HarnessNaming {

    /** `:components:lib-kobweb:ui` becomes `m_components_lib_kobweb_ui`, a valid package segment. */
    private fun moduleSegment(gradlePath: String): String {
        val sanitized = gradlePath.map { character ->
            if (character.isLetterOrDigit()) character.lowercaseChar() else '_'
        }
        return MODULE_SEGMENT_PREFIX + sanitized.joinToString(separator = "")
    }

    fun registryPackage(gradlePath: String): String = "$PAGE_PACKAGE.${moduleSegment(gradlePath)}"

    fun registryFqn(gradlePath: String): String = "${registryPackage(gradlePath)}.$REGISTRY_CLASS"

    fun packageDirectory(packageName: String): String = packageName.replace('.', '/')

    companion object {
        const val PAGE_PACKAGE = "composehtmlpreview.generated"
        const val REGISTRY_CLASS = "PreviewRegistry"
        const val HEADER = "// Generated by the Compose HTML Preview plugin. Do not edit, do not commit."
        private const val MODULE_SEGMENT_PREFIX = "m"
    }
}
