package com.makeevrserg.compose.html.preview.harness.generator

import com.makeevrserg.compose.html.preview.harness.HarnessLayout
import com.makeevrserg.compose.html.preview.harness.HarnessPlan
import com.makeevrserg.compose.html.preview.harness.PreviewPagePath
import com.makeevrserg.compose.html.preview.host.DevServerKind

/**
 * The init script that hands the generated sources to Gradle. It is passed to the preview run only, so
 * the build files of the project stay untouched and every other build sees the project as it is.
 *
 * Sources are added from `beforeProject`, before the build script of the module declares its targets:
 * `configureEach` then reaches the source set whenever the module creates it. The host of a plain
 * Kotlin/JS preview additionally becomes an application: the module may well be a library, and a library
 * has no dev server to run.
 *
 * Its webpack configuration, on the other hand, is applied after the build script has run, because Kotlin
 * applies those in order and the last one wins: a module that names its own bundle or fixes its own port
 * would otherwise serve the preview page from somewhere the plugin does not look.
 */
class PreviewInitScriptFactory(private val layout: HarnessLayout) {

    /** Single quotes keep Groovy from interpreting `$`; backslashes of Windows paths need escaping. */
    private fun groovyString(value: String): String {
        val escaped = value.replace("\\", "\\\\").replace("'", "\\'")
        return "'$escaped'"
    }

    private fun groovyStringList(values: List<String>): String {
        return values.joinToString(prefix = "[", postfix = "]") { value -> groovyString(value) }
    }

    private fun injectionEntry(
        gradlePath: String,
        kotlinDirectory: String,
        resourcesDirectory: String?,
        devServerPort: Int?,
        excludedSourcePaths: List<String>
    ): List<String> {
        return buildList {
            add("    ${groovyString(gradlePath)}: [")
            add("        kotlinSrcDir: ${groovyString(kotlinDirectory)},")
            add("        resourcesSrcDir: ${resourcesDirectory?.let(::groovyString) ?: "null"},")
            add("        devServerPort: ${devServerPort ?: "null"},")
            add("        outputFileName: ${groovyString(PreviewPagePath.WEBPACK_BUNDLE_NAME)},")
            add("        excludedSourcePaths: ${groovyStringList(excludedSourcePaths)}")
            add("    ],")
        }
    }

    /** Groovy accepts a trailing comma in a map literal, but a generated file should read like one written by hand. */
    private fun List<String>.withoutTrailingComma(): List<String> {
        val lastEntryIndex = indexOfLast { line -> line.endsWith(MAP_ENTRY_END) }
        if (lastEntryIndex < 0) return this
        return mapIndexed { index, line ->
            if (index == lastEntryIndex) line.removeSuffix(MAP_ENTRY_SEPARATOR) else line
        }
    }

    private fun injections(plan: HarnessPlan): List<String> {
        val hostDirectory = plan.host.directory
        val isWebpack = plan.host.kind == DevServerKind.WEBPACK
        val registryOnlyModules = plan.modules.filterNot { module -> module.directory == hostDirectory }
        return buildList {
            add("def previewInjections = [")
            registryOnlyModules.forEach { module ->
                addAll(
                    injectionEntry(
                        gradlePath = module.gradlePath,
                        kotlinDirectory = layout.kotlinRoot(module.directory).toString(),
                        resourcesDirectory = null,
                        devServerPort = null,
                        excludedSourcePaths = emptyList()
                    )
                )
            }
            addAll(
                injectionEntry(
                    gradlePath = plan.host.gradlePath,
                    kotlinDirectory = layout.kotlinRoot(hostDirectory).toString(),
                    resourcesDirectory = layout.resourcesRoot(hostDirectory).toString().takeIf { isWebpack },
                    devServerPort = plan.host.devServerPort,
                    excludedSourcePaths = plan.host.excludedSourcePaths
                )
            )
            add("]")
        }.withoutTrailingComma()
    }

    fun create(plan: HarnessPlan): GeneratedFile {
        val lines = buildList {
            add(GROOVY_HEADER)
            add("")
            addAll(injections(plan))
            add("")
            addAll(SCRIPT_BODY)
        }
        return GeneratedFile(
            relativePath = HarnessLayout.INIT_SCRIPT_NAME,
            content = lines.joinToString(separator = "\n", postfix = "\n")
        )
    }

    private companion object {
        const val GROOVY_HEADER = "// Generated by the Compose HTML Preview plugin. Do not edit, do not commit."
        const val MAP_ENTRY_END = "],"
        const val MAP_ENTRY_SEPARATOR = ","

        val SCRIPT_BODY = listOf(
            "def configurePreviewServer = { project, injection ->",
            "    def kotlin = project.extensions.getByName('kotlin')",
            "    kotlin.js { target ->",
            "        target.browser { browser ->",
            "            browser.commonWebpackConfig { config ->",
            "                config.outputFileName = injection.outputFileName",
            "                def devServer = config.devServer",
            "                if (devServer == null) {",
            "                    devServer = config.getClass().getClassLoader()",
            "                        .loadClass('org.jetbrains.kotlin.gradle.targets.js.webpack." +
                "KotlinWebpackConfig\$DevServer')",
            "                        .getDeclaredConstructor().newInstance()",
            "                    config.devServer = devServer",
            "                }",
            "                devServer.port = injection.devServerPort",
            "                devServer.open = false",
            "            }",
            "        }",
            "    }",
            "}",
            "",
            "def injectPreviewSources = { project, injection, sourceSetName ->",
            "    def kotlin = project.extensions.getByName('kotlin')",
            "    if (injection.devServerPort != null) {",
            "        kotlin.js { target -> target.binaries.executable() }",
            "        // Applied after the build script of the module: the last webpack configuration wins,",
            "        // and the page has to be served under the name and on the port the plugin expects.",
            "        project.afterEvaluate { evaluated -> configurePreviewServer(evaluated, injection) }",
            "    }",
            "    kotlin.sourceSets.configureEach { sourceSet ->",
            "        if (sourceSet.name != sourceSetName) return",
            "        sourceSet.kotlin.srcDir(injection.kotlinSrcDir)",
            "        injection.excludedSourcePaths.each { pattern -> sourceSet.kotlin.exclude(pattern) }",
            "        if (injection.resourcesSrcDir != null) sourceSet.resources.srcDir(injection.resourcesSrcDir)",
            "    }",
            "}",
            "",
            "gradle.beforeProject { project ->",
            "    def injection = previewInjections[project.path]",
            "    if (injection == null) return",
            "    project.pluginManager.withPlugin('org.jetbrains.kotlin.multiplatform') {",
            "        injectPreviewSources(project, injection, 'jsMain')",
            "    }",
            "    project.pluginManager.withPlugin('org.jetbrains.kotlin.js') {",
            "        injectPreviewSources(project, injection, 'main')",
            "    }",
            "}"
        )
    }
}
